### ISSUE TITLE
v0.17 renders using Plotly v4 default templates

### ISSUE THREAD

**Issue by nicolaskruchten** [santosjorge/cufflinks#213]
Issue #212 is one example of subtle differences that crop up with v0.17 because we don't opt out of the default Plotly template here. Another is that titles are now no longer centered by default. I have a partial fix but it works for `.figure()` only and not `.iplot()`

**Comment by nicolaskruchten** [comment]
The easiest thing is probably to override whichever defaults are not appreciated in the existing `themes.py` file, such as adding `layout.hovermode = 'x'` etc.

Re-centering the title will likely be a bit more complicated because `layout.title` used to be a string and is now an object, so if we set `layout.title = { ... }` in `themes.py` and then the rest of the code writes a string to `layout.title` it will get overwritten, so we'd need to find every instance where we write to `layout.title` and have it write to `layout.title.text`.

**Comment by fernandascovino** [comment]
Hi! Any updates on title centering? Trying to use `x`, `xanchor` and `xref` doesn't work on a customized theme...

```yaml
layout:
  title: {x: 0.5, xanchor: 'center', xref: 'container'}
```

**Comment by fernandascovino** [comment]
Update: actually worked here!

```yaml
layout:
  title_x: 0.5
```

**Comment by LuisSousaSilva** [comment]
@fernandascovino I'm having the same problem. Can you include a reproducible example please? Don't know where i should put the 
```
layout:
  title_x: 0.5
```

Thank you

**Comment by fernandascovino** [comment]
Of course! So, I've put it into a yaml file, like the one below (named `cufflinks_template.yaml`)

```yaml
layout:
  height: 500
  legend:
    font: {size: 12}
    traceorder: normal
  paper_bgcolor: white
  plot_bgcolor: white
  title_x: 0.5 # here the line!
  width: 700
  xaxis:
    automargin: true
    titlefont: 
        size: 16 
    zerolinecolor: black
    zerolinewidth: 2
  yaxis:
    automargin: true
    tickfont: {size: 15}
    titlefont: 
        size: 16
    zerolinecolor: black
    zerolinewidth: 2
```

And then in Jupyter you can call like this:

```python3
import cufflinks as cf

# Setting cuffilinks template - use it with .iplot(theme='custom')
cf.themes.THEMES['custom'] = yaml.load(open([_themes_path_] / 'cufflinks_template.yaml', 'r'))

df.iplot(theme='custom', title=iplottitle('Plotting a graph with custom theme'))
```

If you want to check out more, I made it into a project here (the `example.ipynb` has it when you run): https://github.com/JoaoCarabetta/project-templates/tree/master/basic/notebooks
