### ISSUE TITLE
How to install cufflinks v0.17.0 via conda?

### ISSUE THREAD

**Issue by murilobellatini** [santosjorge/cufflinks#226]
Hello y'all!

I wasn't able to install `cufflinks` v0.17.0 via `conda`. The only two distributions I found are below:

- https://anaconda.org/conda-forge/cufflinks-py
- https://anaconda.org/conda-forge/python-cufflinks

Can someone shine a little 💡 on this matter?

Thanks!

**Comment by timkpaine** [comment]
@cshaley @dhirschfeld mind consolidating into 1

**Comment by murilobellatini** [comment]
@timkpaine, achieved goal via `pip install` workaround on conda `environment.yml` as of below.
```yml
name: example-env
channels:
  - anaconda-fusion
  - defaults
  - conda-forge
dependencies:
  - python>=3.7.5
  - pandas>=0.25.2
  - plotly>=4.0.0
  - plotly-orca>=1.2.1
  - pip:
    - cufflinks>=0.17.0
```
